package render

import (
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/kabumatome/toroute/internal/config"
)

var hardDenied = map[string]string{
	"user": "process identity is fixed by the image", "runasdaemon": "foreground mode is mandatory",
	"datadirectory": "managed by TOROUTE_DATA_DIR", "cachedirectory": "managed by ToRoute", "keydirectory": "server roles are unsupported",
	"pidfile": "managed by ToRoute", "controlport": "TCP control ports are disabled", "controlsocket": "managed by ToRoute",
	"controlsocketsgroupwritable": "managed by ToRoute", "cookieauthentication": "SAFECOOKIE is mandatory", "cookieauthfile": "managed by ToRoute",
	"cookieauthfilegroupreadable": "managed by ToRoute", "hashedcontrolpassword": "TCP control credentials are unsupported",
	"socksport": "managed by TOROUTE_SOCKS_ADDRESS", "sockspolicy": "managed by ToRoute", "safesocks": "remote DNS safety is mandatory",
	"httptunnelport": "use the optional HTTP adapter", "transport": "transparent proxying is unsupported", "transproxytype": "transparent proxying is unsupported",
	"dnsport": "external DNS proxying is unsupported", "orport": "relay mode is unsupported", "dirport": "relay mode is unsupported",
	"extorport": "relay mode is unsupported", "exitrelay": "exit relay mode is unsupported", "exitpolicy": "exit relay mode is unsupported",
	"bridgerelay": "bridge relay mode is unsupported", "servertransportplugin": "server transports are unsupported",
	"hiddenservicedir": "onion service hosting is outside scope", "hiddenserviceport": "onion service hosting is outside scope",
	"clientonly": "client-only mode is mandatory", "log": "logging destination is managed by ToRoute",
	"bridge": "bridge lines must use the validated secret-file interface", "usebridges": "managed by TOROUTE_BRIDGES_FILE",
	"clienttransportplugin": "pluggable transport execution is managed by ToRoute", "exitnodes": "managed by TOROUTE_EXIT_COUNTRIES",
	"excludeexitnodes": "managed by TOROUTE_EXCLUDE_EXIT_COUNTRIES", "strictnodes": "managed by TOROUTE_STRICT_EXIT",
	"geoipfile": "GeoIP data is supplied by the image", "geoip6file": "GeoIP data is supplied by the image",
	"dirauthority": "directory trust roots cannot be replaced", "alternatedirauthority": "directory trust roots cannot be replaced",
	"alternatebridgeauthority": "directory trust roots cannot be replaced", "authoritativedirectory": "directory authority mode is unsupported",
	"versioningauthoritativedirectory": "directory authority mode is unsupported", "dircache": "directory server mode is unsupported",
	"dirpolicy": "directory server policy is unsupported", "dirportfrontpage": "directory server mode is unsupported",
	"fallbackdir": "directory fallback trust cannot be replaced", "mapaddress": "destination rewriting is outside scope",
	"clientonionauthdir": "onion client credentials are outside scope", "httpproxy": "upstream proxy chaining is outside scope",
	"httpsproxy": "upstream proxy chaining is outside scope", "httpsproxyauthenticator": "proxy credentials must not be injected",
	"socks4proxy": "upstream proxy chaining is outside scope", "socks5proxy": "upstream proxy chaining is outside scope",
	"socks5proxyusername": "proxy credentials must not be injected", "socks5proxypassword": "proxy credentials must not be injected",
	"address": "relay publication identity is unsupported", "addressdisableipv6": "relay publication identity is unsupported",
	"assumereachable": "relay reachability publication is unsupported", "ipv6exit": "exit relay mode is unsupported",
}

var safeAllowed = map[string]func([]string) error{
	"avoiddiskwrites": requireExact("1"), "circuitbuildtimeout": requireIntegerRange(10, 300),
	"connectionpadding": requireOneOf("auto", "1"), "fascistfirewall": requireExact("1"),
	"learncircuitbuildtimeout": requireExact("1"), "maxcircuitdirtiness": requireIntegerRange(60, 86400),
	"newcircuitperiod": requireIntegerRange(30, 3600), "testsocks": requireExact("1"),
}

func Torrc(cfg config.Config) (string, error)         { return torrc(cfg, false) }
func RedactedTorrc(cfg config.Config) (string, error) { return torrc(cfg, true) }

func torrc(cfg config.Config, redact bool) (string, error) {
	lines := []string{
		"# Generated by ToRoute. Do not edit this runtime file.", "ClientOnly 1", "RunAsDaemon 0",
		"DataDirectory " + cfg.DataDir, "PidFile " + cfg.TorPIDPath(),
		"SocksPort " + cfg.SocksAddress + " IsolateClientAddr IsolateSOCKSAuth", "SafeSocks 1",
		"ControlPort 0", "ControlSocket " + cfg.ControlSocketPath(), "ControlSocketsGroupWritable 0",
		"CookieAuthentication 1", "CookieAuthFile " + cfg.CookiePath(), "CookieAuthFileGroupReadable 0",
		"SafeLogging 1", "ClientRejectInternalAddresses 1", "Log " + cfg.LogLevel + " stdout",
	}
	if len(cfg.ExitCountries) > 0 {
		lines = append(lines, "ExitNodes "+countrySet(cfg.ExitCountries))
		if cfg.StrictExit {
			lines = append(lines, "StrictNodes 1")
		}
	}
	if len(cfg.ExcludeExitCountries) > 0 {
		lines = append(lines, "ExcludeExitNodes "+countrySet(cfg.ExcludeExitCountries))
	}
	if cfg.BridgesFile != "" {
		bridges, err := bridgeLines(cfg.BridgesFile, redact)
		if err != nil {
			return "", fmt.Errorf("bridges: %w", err)
		}
		lines = append(lines, "UseBridges 1", "ClientTransportPlugin obfs4 exec "+cfg.Obfs4ProxyBinary)
		lines = append(lines, bridges...)
	}
	if cfg.TorrcAppendFile != "" {
		fragment, err := appendFragment(cfg.TorrcAppendFile)
		if err != nil {
			return "", fmt.Errorf("torrc append file: %w", err)
		}
		if len(fragment) > 0 {
			lines = append(lines, "", "# Validated user fragment follows.")
			lines = append(lines, fragment...)
		}
	}
	return strings.Join(lines, "\n") + "\n", nil
}

func Privoxy(cfg config.Config) string {
	if !cfg.HTTPEnabled {
		return ""
	}
	host, port, err := net.SplitHostPort(cfg.SocksAddress)
	if err != nil {
		host, port = "127.0.0.1", "9050"
	}
	switch host {
	case "0.0.0.0", "localhost":
		host = "127.0.0.1"
	case "::":
		host = "::1"
	}
	target := net.JoinHostPort(host, port)
	return strings.Join([]string{
		"# Generated by ToRoute. Filtering and destination logging are disabled.",
		"confdir /etc/privoxy", "templdir /etc/privoxy/templates", "logdir " + cfg.RuntimeDir,
		"listen-address " + cfg.HTTPAddress, "toggle 0", "enable-remote-toggle 0", "enable-remote-http-toggle 0",
		"enable-edit-actions 0", "enforce-blocks 0", "accept-intercepted-requests 0",
		"forward-socks5t / " + target + " .", "logfile /dev/stdout", "debug 4096",
	}, "\n") + "\n"
}

func countrySet(countries []string) string {
	items := append([]string(nil), countries...)
	sort.Strings(items)
	for i := range items {
		items[i] = "{" + items[i] + "}"
	}
	return strings.Join(items, ",")
}

var fingerprintPattern = regexp.MustCompile(`^[A-Fa-f0-9]{40}$`)

func bridgeLines(path string, redact bool) ([]string, error) {
	raw, err := config.ReadSecretLines(path, 1<<20, 16<<10)
	if err != nil {
		return nil, err
	}
	var out []string
	for n, line := range raw {
		text := strings.TrimSpace(line)
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		if strings.HasPrefix(strings.ToLower(text), "bridge ") {
			text = strings.TrimSpace(text[7:])
		}
		fields := strings.Fields(text)
		if err := validateObfs4Bridge(fields); err != nil {
			return nil, fmt.Errorf("line %d: %w", n+1, err)
		}
		if redact {
			out = append(out, "Bridge [REDACTED]")
		} else {
			out = append(out, "Bridge "+strings.Join(fields, " "))
		}
		if len(out) > 100 {
			return nil, errors.New("maximum 100 bridge lines")
		}
	}
	if len(out) == 0 {
		return nil, errors.New("no usable obfs4 bridge lines found")
	}
	return out, nil
}

func validateObfs4Bridge(fields []string) error {
	if len(fields) < 5 || strings.ToLower(fields[0]) != "obfs4" {
		return errors.New("must contain obfs4, IP:port, fingerprint, cert, and iat-mode")
	}
	host, portText, err := net.SplitHostPort(fields[1])
	if err != nil {
		return fmt.Errorf("bridge address must be IP:port: %w", err)
	}
	if net.ParseIP(host) == nil {
		return errors.New("bridge host must be an IP literal")
	}
	port, err := strconv.Atoi(portText)
	if err != nil || port < 1 || port > 65535 {
		return errors.New("bridge port must be 1..65535")
	}
	if !fingerprintPattern.MatchString(fields[2]) {
		return errors.New("fingerprint must be exactly 40 hexadecimal characters")
	}
	params := map[string]string{}
	for _, field := range fields[3:] {
		parts := strings.SplitN(field, "=", 2)
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return fmt.Errorf("invalid parameter %q", field)
		}
		key := strings.ToLower(parts[0])
		if key != "cert" && key != "iat-mode" {
			return fmt.Errorf("unsupported parameter %q", parts[0])
		}
		if _, exists := params[key]; exists {
			return fmt.Errorf("duplicate parameter %q", parts[0])
		}
		params[key] = parts[1]
	}
	cert, ok := params["cert"]
	if !ok {
		return errors.New("cert is required")
	}
	if len(cert) > 4096 {
		return errors.New("cert is too long")
	}
	for _, r := range cert {
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || strings.ContainsRune("+/=_-", r)) {
			return fmt.Errorf("cert contains unsupported character %q", r)
		}
	}
	mode, ok := params["iat-mode"]
	if !ok || (mode != "0" && mode != "1") {
		return errors.New("iat-mode must be 0 or 1")
	}
	return nil
}

func appendFragment(path string) ([]string, error) {
	raw, err := config.ReadLines(path, 1<<20, 16<<10)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var out []string
	for n, line := range raw {
		text := strings.TrimSpace(line)
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		if strings.HasPrefix(text, "%") || strings.HasPrefix(text, "+") || strings.HasPrefix(text, "/") {
			return nil, fmt.Errorf("line %d uses include/add/remove syntax", n+1)
		}
		fields := strings.Fields(text)
		if len(fields) < 2 {
			return nil, fmt.Errorf("line %d is incomplete", n+1)
		}
		key := strings.ToLower(fields[0])
		if reason, blocked := blockedDirective(key); blocked {
			return nil, fmt.Errorf("line %d: %s is blocked: %s", n+1, fields[0], reason)
		}
		validator, ok := safeAllowed[key]
		if !ok {
			return nil, fmt.Errorf("line %d: %s is not in the reviewed client-tuning allowlist", n+1, fields[0])
		}
		if seen[key] {
			return nil, fmt.Errorf("line %d: duplicate directive %s", n+1, fields[0])
		}
		if err := validator(fields[1:]); err != nil {
			return nil, fmt.Errorf("line %d: invalid %s value: %w", n+1, fields[0], err)
		}
		seen[key] = true
		out = append(out, strings.Join(fields, " "))
	}
	return out, nil
}

func blockedDirective(key string) (string, bool) {
	if strings.HasPrefix(key, "_") {
		return "internal/testing directives are not accepted", true
	}
	if reason, ok := hardDenied[key]; ok {
		return reason, true
	}
	for _, prefix := range []string{"hiddenservice", "onionservice", "clientonionauth", "clienttransport", "servertransport", "publishserver", "control", "socks", "dns", "trans", "natd", "metrics", "extor", "orport", "dirport", "dircache", "dirpolicy", "dirauthority", "alternatedirauthority", "alternatebridgeauthority", "fallbackdir", "bridgeauthoritative", "authoritative", "versioningauthoritative", "v3auth", "relay", "bandwidth", "accounting", "outboundbind", "contactinfo", "nickname", "myfamily", "testing", "authdir", "dirserv"} {
		if strings.HasPrefix(key, prefix) {
			return "outside the client-only security boundary", true
		}
	}
	if strings.HasPrefix(key, "exitpolicy") || key == "ipv6exit" {
		return "exit relay policy is unsupported", true
	}
	if strings.HasSuffix(key, "statistics") {
		return "relay/service statistics are outside the privacy boundary", true
	}
	if strings.HasSuffix(key, "port") {
		return "additional listeners are blocked", true
	}
	return "", false
}

func requireExact(want string) func([]string) error {
	return func(v []string) error {
		if len(v) != 1 || v[0] != want {
			return fmt.Errorf("must be exactly %q", want)
		}
		return nil
	}
}
func requireOneOf(allowed ...string) func([]string) error {
	return func(v []string) error {
		if len(v) != 1 {
			return fmt.Errorf("must be one of %s", strings.Join(allowed, ", "))
		}
		for _, a := range allowed {
			if v[0] == a {
				return nil
			}
		}
		return fmt.Errorf("must be one of %s", strings.Join(allowed, ", "))
	}
}
func requireIntegerRange(min, max int) func([]string) error {
	return func(v []string) error {
		if len(v) != 1 {
			return fmt.Errorf("must be one integer in %d..%d", min, max)
		}
		n, e := strconv.Atoi(v[0])
		if e != nil || n < min || n > max {
			return fmt.Errorf("must be an integer in %d..%d", min, max)
		}
		return nil
	}
}

func WriteAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".toroute-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}
